Add "join table" for visits
The-Normal-One1/Vet-clinic-database pull request #10
Opened 2023-03-30 20:27 UTC by The-Normal-One1

### The following lists were made to add the `join table`:

- [ ] Created a table named `vets`
- [ ] Created a "join table" called `specializations` to handle the relationship.
- [ ] Created a "join table" called `visits` to handle the relationship, it also kept track of the date of the visit.
- [ ] Inserted data for `vets`
- [ ] Inserted data for `specialties`
- [ ] Inserted data for `visits`
- [ ] Wrote queries

1. Who was the last animal seen by William Tatcher?
![q1](https://user-images.githubusercontent.com/112026887/228956067-8cad3f54-c913-4cb0-a173-b8117295faf1.png)

2. How many different animals did Stephanie Mendez see?
![q2](https://user-images.githubusercontent.com/112026887/228956087-5b3084aa-3aa5-40a8-a024-d19ed45012df.png)

3. List all vets and their specialties, including vets with no specialties.
![q3](https://user-images.githubusercontent.com/112026887/228956101-af3f6893-1751-48ba-b5f5-de2403d1e681.png)

4. List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
![q4](https://user-images.githubusercontent.com/112026887/228956123-6a88d97f-ae27-4d79-bb95-fb313380a884.png)

5. What animal has the most visits to vets?
![q5](https://user-images.githubusercontent.com/112026887/228956141-4bd9b8c4-c35b-431d-b1c3-ecd0110c14c8.png)

6. Who was Maisy Smith's first visit?
![q6](https://user-images.githubusercontent.com/112026887/228956217-2997b192-b7a3-46ac-ba69-b13f220f430c.png)

7. Details for most recent visit: animal information, vet information, and date of visit.
![q7-1](https://user-images.githubusercontent.com/112026887/228956247-36dbbda2-5cf1-4d00-b5be-69f3ce58fa89.png)
![q7-2](https://user-images.githubusercontent.com/112026887/228956266-a0be8388-9f40-48ce-9fff-4f3d96ce049f.png)

8. How many visits were with a vet that did not specialize in that animal's species?
![q8](https://user-images.githubusercontent.com/112026887/228956292-8cc93e8f-309f-42b9-856a-e0d70a845a3e.png)

9. What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![q9](https://user-images.githubusercontent.com/112026887/228956311-0e1475cb-6e37-4144-ba41-48d33f75824e.png)

2023-03-30 20:46 UTC, BertrandConxy requested changes
Hi @The-Normal-One1, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 20:46 UTC, BertrandConxy commented on schema.sql
> +SELECT * FROM animals
- [x] Good job so far 👏 👏 Since these `Select` commands are for just querying for data, there is no need to leave them here in your schema file which is supposed to hold the tables creation command, I would suggest that you remove them here in this file 😃 By doing this, you would have followed YAGNI principle

2023-03-30 20:46 UTC, BertrandConxy commented on data.sql
> +SELECT * FROM species
- [x] Again as I mentioned above since these `Select` commands are for just querying for data, there is no need to leave them here in your schema file which is supposed to hold the tables creation command, I would suggest that you remove them here in this file 😃 I could say that by doing this, you will have followed the YAGNI principle which is among the coding best practices that we are expected to follow every day 👍

2023-03-31 05:57 UTC, arslanbisharat commented
Hi @The-Normal-One1,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 06:02 UTC, merged